name: Deployment
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feat/**'
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get CWD and all of its files
        run: pwd && ls -laR
      - name: Install dependencies for linting
        run: pip install -r requirements-test.txt
      - name: Lint
        run: python lint.py
      - name: Test
        run: pytest tests.py
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ger code
        uses: actions/checkout@v3
      - name: Deploy
        run: python deploy.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact'
          path: |
            deployed.txt
            package.json
            dist
          retention-days: 10
  download:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get built artifacts
        uses: actions/download-artifact@v3
        with: # We need to know what file o download
          name: deployed.txt
      - name: Display all files
        run: ls


