name: Testing
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  push:
    branches:
      - 'main'
      - 'master'
      - 'feat/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code # Download the code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: utput github context
        run: echo "${{ toJSON(github) }}"